<?php

namespace App\Sevices\AddressParser;

class FakeParser implements ParserInterface
{

    public function clean(string $address): array
    {
        return [
            "source"                  => "ногинск 8-я молзинская 14",
            "result"                  => "Московская обл, г Ногинск, ул 8-ая Молзинская, д 14",
            "postal_code"             => "142411",
            "country"                 => "Россия",
            "country_iso_code"        => "RU",
            "federal_district"        => "Центральный",
            "region_fias_id"          => "29251dcf-00a1-4e34-98d4-5c47484a36d4",
            "region_kladr_id"         => "5000000000000",
            "region_iso_code"         => "RU-MOS",
            "region_with_type"        => "Московская обл",
            "region_type"             => "обл",
            "region_type_full"        => "область",
            "region"                  => "Московская",
            "area_fias_id"            => "40ae04e3-9a69-44ea-8bd7-6c6f08e1a4ca",
            "area_kladr_id"           => "5004300000000",
            "area_with_type"          => "г Ногинск",
            "area_type"               => "г",
            "area_type_full"          => "город",
            "area"                    => "Ногинск",
            "city_fias_id"            => null,
            "city_kladr_id"           => null,
            "city_with_type"          => null,
            "city_type"               => null,
            "city_type_full"          => null,
            "city"                    => null,
            "city_area"               => null,
            "city_district_fias_id"   => null,
            "city_district_kladr_id"  => null,
            "city_district_with_type" => null,
            "city_district_type"      => null,
            "city_district_type_full" => null,
            "city_district"           => null,
            "settlement_fias_id"      => null,
            "settlement_kladr_id"     => null,
            "settlement_with_type"    => null,
            "settlement_type"         => null,
            "settlement_type_full"    => null,
            "settlement"              => null,
            "street_fias_id"          => "29d0a8b9-fa60-4b24-8fb2-b9a5f331edbd",
            "street_kladr_id"         => "50043000000121700",
            "street_with_type"        => "ул 8-ая Молзинская",
            "street_type"             => "ул",
            "street_type_full"        => "улица",
            "street"                  => "8-ая Молзинская",
            "stead_fias_id"           => null,
            "stead_kladr_id"          => null,
            "stead_cadnum"            => null,
            "stead_type"              => null,
            "stead_type_full"         => null,
            "stead"                   => null,
            "house_fias_id"           => "65ecfeec-e23a-4fc6-bd9b-255f42f223dc",
            "house_kladr_id"          => "5004300000012170015",
            "house_cadnum"            => "50:16:0301011:581",
            "house_type"              => "д",
            "house_type_full"         => "дом",
            "house"                   => "14",
            "block_type"              => null,
            "block_type_full"         => null,
            "block"                   => null,
            "entrance"                => null,
            "floor"                   => null,
            "flat_fias_id"            => null,
            "flat_cadnum"             => null,
            "flat_type"               => null,
            "flat_type_full"          => null,
            "flat"                    => null,
            "flat_area"               => "70.8",
            "square_meter_price"      => null,
            "flat_price"              => null,
            "postal_box"              => null,
            "fias_id"                 => "65ecfeec-e23a-4fc6-bd9b-255f42f223dc",
            "fias_code"               => "50043000000000012170015",
            "fias_level"              => "8",
            "fias_actuality_state"    => "0",
            "kladr_id"                => "5004300000012170015",
            "capital_marker"          => "0",
            "okato"                   => "46451000000",
            "oktmo"                   => "46751000001",
            "tax_office"              => "5031",
            "tax_office_legal"        => "5031",
            "timezone"                => "UTC+3",
            "geo_lat"                 => "55.8862971",
            "geo_lon"                 => "38.4187635",
            "beltway_hit"             => "OUT_MKAD",
            "beltway_distance"        => "38",
            "qc_geo"                  => 0,
            "qc_complete"             => 5,
            "qc_house"                => 2,
            "qc"                      => 0,
            "unparsed_parts"          => null,
            "metro"                   => null,
        ];
    }
}
